---

- name: Nginx Server
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Update Instances
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: install nginx server
      apt:
        name: nginx
        state: latest
    - name: start nginx server
      ansible.builtin.service:
